[package]
name = "pest3_derive"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
pest3_generator.workspace = true

[dev-dependencies]
pest3.workspace = true
anyhow = "1"
