[package]
name = "pest3_derive"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
pest3_generator = { workspace = true, path = "../generator", version = "0.0.0-prealpha0" }

[dev-dependencies]
pest3 = { workspace = true, path = "../pest", version = "0.0.0-prealpha0" }
anyhow = "1"
