[package]
name = "pest3"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
unicode-width.workspace = true
pest2.workspace = true
